# Generated by Django 4.2.16 on 2024-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10, verbose_name='Role')),
                ('events', models.ManyToManyField(to='events.event')),
            ],
        ),
    ]
