# Generated by Django 4.2.16 on 2024-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tguser_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='role',
            field=models.CharField(default='user', max_length=10, verbose_name='Role'),
        ),
    ]
